format_version: 10
pipelines:
  Test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ddaaf85:
        git: https://github.com/Santhosh-Grandhi/Gocd
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Test-s:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            Test-j:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
