format_version: 10
pipelines:
  Demo-Pipeline:
    group: DemoGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ddaaf85:
        git: https://github.com/Santhosh-Grandhi/Gocd
        shallow_clone: true
        auto_update: true
        branch: main

#    environment_variables:
#      - component: test
    stages:
      - Dev:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
              environment_variables:
               Component: Hello
